import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import CardanoClientProvider from "@/providers/cardano-client-provider";
import { WalletWidget } from "@/components/wallet-widget";
import { WalletSelect } from "@/components/wallet-select";
import { Toaster } from "sonner";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <ConvexClientProvider>
          <CardanoClientProvider/>
          <Toaster />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
