import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import CardanoClientProvider from "@/providers/cardano-client-provider";
import { WalletWidget } from "@/components/wallet-widget";
import { ClientTesting } from "@/components/clientTesting";
import { WalletSelect } from "@/components/wallet-select";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <CardanoClientProvider>
            <WalletWidget />
            <WalletSelect/>
            {/* <ClientTesting /> */}
          </CardanoClientProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
